export { default as Topimage } from './Topimage/'
export { default as Projectdescription } from './Projectdescription'
export { default as Outcomes } from './Outcomes'
export { default as Contentwrap } from './Contentwrap'
export { default as Demoday } from './Demoday'
export { default as Recognition } from './Recognition'
export { default as Getintouch } from './Getintouch'
